version: 2.1
jobs:
  orbs:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install   
workflows:
  version: 2.1
  orbs:
    heroku: circleci/heroku@0.0.10
  workflows:
    heroku_deploy:
      jobs:
        - heroku/deploy-via-git    
